version: '2'
services:
  yellowfin:
    container_name: yellowfin
    hostname: yellowfin-dev-1
    image: yellowfin
    build:
      context: yellowfin/.
      args:
        YELLOWFIN_VERSION: 20180226
    ports:
      - 7900:7900
    links:
      - postgres
    volumes:
      - ./yellowfin_installation:/applications/yellowfin:rw
      - ./license:/license:ro
  postgres:
    container_name: postgres
    image: postgres:9.4.4
    ports:
      - 7800:5432
