version: '2'
services:
  yellowfin:
    container_name: yellowfin
    hostname: yellowfin-dev-1
    image: yellowfin
    build:
      context: yellowfin/.
      args:
        YELLOWFIN_VERSION: 20170928
    ports:
      - "7900:7900"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./yellowfin_installation:/application/yellowfin:rw
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
